name: Angular Image CI
on:
    push:
        branches: [ main ]
    pull_request:
        types: [ opened, reopened, synchronize ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Build Angular image
                run: docker-compose build angular

            -   name: Use Node.js 17.x
                uses: actions/setup-node@v3
                with:
                    node-version: 17.x
                    cache: 'npm'
            -   run: npm ci
            -   run: npm run build --if-present
            -   run: npm test
