name: Angular 2 Image CI
on:
    push:
        branches: [ main ]
    pull_request:
        types: [ opened, reopened, synchronize ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Build Angular 2 image
                run: docker build . --file angular2/Dockerfile --tag angular2:$(date +%s)

