name: MySQL Image CI
on:
    push:
        branches: [ main ]
    pull_request:
        types: [ opened, reopened, synchronize ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Build the SQL volume
                run: docker volume create --name=rsvn-mysql-db
            -   name: Build MySQL image
                run: docker-compose build mysql

